### PR TITLE
improve projects page

### PR DESCRIPTION
**Pull request by ik04**
changed some designs, review required
Screenshot from 2023-07-09 18-09-33
todo: fix these styles and add them to a db or cms (firebase or sanity)
Screenshot from 2023-07-09 18-09-39

### CODE REVIEW

**Comment by jatindotdev** [comment]
The landing is too big to display as a first page, maybe lower the font size of the description @ik04

**Comment by jatindotdev** [comment]
also for the slider if you think it's going to be hard to make that responsive or good looking maybe we can look for some other better slider component

**Review by jatindotdev — CHANGES_REQUESTED** [review]
Check the comments for the changes requested

**Comment by ik04** [comment]
aight i'll look into it, thx fr the suggestions

**Pull request closed without merging**
